services:
  eureka-server:
    image: nbzhk/eureka-server:latest
    ports:
      - "8761:8761"
    networks:
      - e-com-network

  api-gateway:
    image: nbzhk/api-gateway:latest
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    depends_on:
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      AUTH_SERVICE_HOST: auth-service
      USER_SERVICE_HOST: user-service
      PRODUCT_SERVICE_HOST: product-service
      CART_SERVICE_HOST: cart-service
    networks:
      - e-com-network

  mysql-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: e-commerce-data-base
    networks:
      - e-com-network
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  user-service:
    image: nbzhk/user-service:latest
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    depends_on:
      - eureka-server
      - mysql-db
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      USER_DB_URL: mysql-db:3306/user_service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    networks:
      - e-com-network

  auth-service:
    image: nbzhk/auth-service:latest
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    depends_on:
      - eureka-server
      - mysql-db
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      AUTH_DB_URL: mysql-db:3306/auth_service
      JWT_SECRET: ${JWT_SECRET}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    networks:
      - e-com-network

  product-service:
    image: nbzhk/product-service:latest
    ports:
      - "${PRODUCT_SERVICE_PORT}:${PRODUCT_SERVICE_PORT}"
    depends_on:
      - eureka-server
      - mysql-db
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      PRODUCT_DB_URL: mysql-db:3306/product_service
      JWT_SECRET: ${JWT_SECRET}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    networks:
      - e-com-network

  cart-service:
    image: nbzhk/cart-service:latest
    ports:
      - "${CART_SERVICE_PORT}:${CART_SERVICE_PORT}"
    depends_on:
      - eureka-server
      - mysql-db
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      CART_DB_URL: mysql-db:3306/cart_service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    networks:
      - e-com-network

networks:
  e-com-network:
    driver: bridge

volumes:
  mysql_data: