name: User-Service build
on:
  push:
    branches: [ "main" ]
    paths: 
      - 'user-service/**'
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'user-service/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file user-service/pom.xml
      
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: user-service-jar
        path: user-service/target/*.jar
        retention-days: 5
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./user-service
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest,${{ secrets.DOCKERHUB_USERNAME }}/user-service:${{ github.sha }}
